package me.ducanh.thesis.util;


import javafx.scene.paint.Color;
import java.util.ArrayList;
import java.util.Arrays;

public class Colors {

    public static Color[] array = {
            Color.TOMATO,
            Color.LIGHTBLUE,
            Color.LIGHTCORAL,
            Color.PALEGREEN,
            Color.LIGHTPINK,
            Color.GOLDENROD,
            Color.HONEYDEW,
            Color.POWDERBLUE,
            Color.PEACHPUFF,
            Color.ORCHID,
            Color.MOCCASIN,
            Color.DARKGREY,
            Color.DARKKHAKI,
            Color.DARKMAGENTA,
            Color.DARKOLIVEGREEN,
            Color.DARKORANGE,
            Color.DARKORCHID,
            Color.DARKRED,
            Color.DARKSALMON,
            Color.DARKSEAGREEN,
            Color.DARKSLATEBLUE,
            Color.DARKSLATEGRAY,
            Color.DARKSLATEGREY,
            Color.DARKTURQUOISE,
            Color.DARKVIOLET,
            Color.DEEPPINK,
            Color.DEEPSKYBLUE,
            Color.DIMGRAY,
            Color.DIMGREY,
            Color.DODGERBLUE,
            Color.FIREBRICK,
            Color.FLORALWHITE,
            Color.FORESTGREEN,
            Color.FUCHSIA,
            Color.GAINSBORO,
            Color.GHOSTWHITE,
            Color.GOLD,
            Color.GRAY,
            Color.GREEN,
            Color.GREENYELLOW,
            Color.GREY,

            Color.HOTPINK,
            Color.INDIANRED,
            Color.INDIGO,
            Color.IVORY,
            Color.KHAKI,
            Color.LAVENDER,
            Color.LAVENDERBLUSH,
            Color.LAWNGREEN,
            Color.LEMONCHIFFON,

            Color.LIGHTCYAN,
            Color.LIGHTGOLDENRODYELLOW,
            Color.LIGHTGRAY,
            Color.LIGHTGREEN,
            Color.LIGHTGREY,

            Color.LIGHTSALMON,
            Color.LIGHTSEAGREEN,
            Color.LIGHTSKYBLUE,
            Color.LIGHTSLATEGRAY,
            Color.LIGHTSTEELBLUE,
            Color.LIGHTYELLOW,
            Color.LIME,
            Color.LIMEGREEN,
            Color.LINEN,
            Color.MAGENTA,
            Color.MAROON,
            Color.MEDIUMAQUAMARINE,
            Color.MEDIUMBLUE,
            Color.MEDIUMORCHID,
            Color.MEDIUMPURPLE,
            Color.MEDIUMSEAGREEN,
            Color.MEDIUMSLATEBLUE,
            Color.MEDIUMSPRINGGREEN,
            Color.MEDIUMTURQUOISE,
            Color.MEDIUMVIOLETRED,
            Color.MIDNIGHTBLUE,
            Color.MINTCREAM,
            Color.MISTYROSE,

            Color.NAVAJOWHITE,
            Color.NAVY,
            Color.OLDLACE,
            Color.OLIVE,
            Color.OLIVEDRAB,
            Color.ORANGE,
            Color.ORANGERED,

            Color.PALEGOLDENROD,

            Color.PALETURQUOISE,
            Color.PALEVIOLETRED,
            Color.PAPAYAWHIP,

            Color.PERU,
            Color.PINK,
            Color.PLUM,

            Color.PURPLE,
            Color.RED,
            Color.ROSYBROWN,
            Color.ROYALBLUE,
            Color.SADDLEBROWN,
            Color.SALMON,
            Color.SANDYBROWN,
            Color.SEAGREEN,
            Color.SEASHELL,
            Color.SIENNA,
            Color.SILVER,
            Color.SKYBLUE,
            Color.SLATEBLUE,
            Color.SLATEGRAY,
            Color.SLATEGREY,
            Color.SNOW,
            Color.SPRINGGREEN,
            Color.STEELBLUE,
            Color.TAN,
            Color.TEAL,
            Color.THISTLE,
            Color.TURQUOISE,
            Color.VIOLET,
            Color.WHEAT,
            Color.WHITE,
            Color.WHITESMOKE,
            Color.YELLOW,
            Color.YELLOWGREEN
    };

}

